name: Python_Docker

on:
  push:
    branches: ['master', 'release-*', 'community-metrics-precommit-migration']
    tags: 'v*'
  pull_request:
    branches: ['master', 'release-*']
    tags: 'v*'
    paths:
      - 'model/**'
      - 'sdks/python/**'
      - 'release/**'

jobs:
  name: Run Python Docker
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credential: false
          submodules: recursive
      - name: Run :pythonDockerBuildPreCommit
        uses: ./.github/actions/gradle-command-self-hosted-action
        with:
          gradle-command: :pythonDockerBuildPreCommit
          gradle-switches: "--info"